# 4a

In [1]:
import numpy as np 
import pandas as pd

In [2]:
import torch

In [3]:
from Q3_func import mse_calc, mae_calc

In [4]:
def normalEquationRegression(X, y):
    x_new = []
    for i in X:
        x_new.append([1]+list(i))
    X = np.array([np.array(i) for i in x_new])
    XtX = np.dot(X.T,X)
    inv = np.linalg.inv(XtX)
    theta = np.dot(inv,np.dot(X.T,y))
    return theta, X

In [5]:
X = [[1,2,5],[3,1,9],[4,5,7],[2,6,4],[2,6,9]]
X = np.array([np.array(i) for i in X])
y = np.array([8,13,16,12,17])
y = y.reshape(len(y),1)

In [6]:
theta, x_new = normalEquationRegression(X, y)
print('X:\n',x_new,'\n')
print('y:\n',y,'\n')
print('Theta:\n',theta,'\n')
pred = np.dot(x_new,theta)
print('Prediction:\n',pred,'\n')
rmse = mse_calc(y, pred)
print('RMSE=',rmse)
print('''RMSE can be considered as zero.
Theta_0 can also be considered as zero''')

X:
 [[1 1 2 5]
 [1 3 1 9]
 [1 4 5 7]
 [1 2 6 4]
 [1 2 6 9]] 

y:
 [[ 8]
 [13]
 [16]
 [12]
 [17]] 

Theta:
 [[  2.84217094e-14]
 [  1.00000000e+00]
 [  1.00000000e+00]
 [  1.00000000e+00]] 

Prediction:
 [[  8.]
 [ 13.]
 [ 16.]
 [ 12.]
 [ 17.]] 

RMSE= [  1.16754085e-14]
RMSE can be considered as zero.
Theta_0 can also be considered as zero


# 4b

In [7]:
def gradientDescentRegression(X, y, alpha = 0.1, iterations=10**5):
    
    n, b = X.shape[0], X.shape[1]
    ones = np.ones((n,1))
    X = np.hstack((ones,X))
    np.random.seed(1)
    theta = np.zeros(( len(X[0]), 1 ))
    #prev_cost = 0
    cost = 0
    m = float(len(y))

    for i in range(iterations):
        pred = np.dot(X, theta)
        #prev_cost = cost
        error = pred - y
        cost = np.sqrt(np.dot(error.T, error))/m
        theta = theta - (alpha/m) * np.dot(X.T, error)
    return theta, x_new

In [8]:
X = [[1,2,3],[1,3,5],[1,2,1],[1,10,12],[4,21,9]]
X = np.array([np.array(i) for i in X])
y = np.array([6,9,4,30,40])
y = y.reshape(len(y),1)

In [9]:
print('X:\n',X,'\n')
print('y:\n',y,'\n')
theta, x_new = gradientDescentRegression(X, y,0.01)
print('Theta:\n',theta,'\n')
pred = np.dot(x_new,theta)
print('Prediction:\n',pred,'\n')
rmse = mse_calc(y, pred)
print('RMSE=',rmse)

X:
 [[ 1  2  3]
 [ 1  3  5]
 [ 1  2  1]
 [ 1 10 12]
 [ 4 21  9]] 

y:
 [[ 6]
 [ 9]
 [ 4]
 [30]
 [40]] 

Theta:
 [[ 2.99642809]
 [-4.03109489]
 [ 2.21332988]
 [ 0.73866941]] 

Prediction:
 [[  7.08534   ]
 [ -0.23550203]
 [  3.10938378]
 [ 11.16889521]
 [ 14.86224226]] 

RMSE= [ 14.65457628]


# 4c

In [10]:
import autograd

In [11]:


def gradientDescentAutogradRegression(X,y,alpha = 0.01):
    iterations = 1000
    n, b = X.shape[0], X.shape[1]
    ones = np.ones((n,1))
    X = np.hstack((ones,X))
    theta = np.zeros((b+1,1))
    
    
    def cost_func(theta):
        #print(X.shape, theta.shape)
        err = y - np.dot(X, theta)
        #print(err.shape)
        return np.dot(err.T, err)
    
    grd = autograd.grad(cost_func)
    
    
    for i in range(iterations):
        delta = grd(theta)
        theta = theta - alpha * delta/n
    
    return theta, x_new
        

In [12]:
X = [[1,2,5],[3,1,9],[4,5,7],[2,6,4],[2,6,9]]

X = np.array([np.array(i) for i in X])
y = np.array([8,13,16,12,17])

y = y.reshape(len(y),1)

In [13]:
print('X:\n',X,'\n')
print('y:\n',y,'\n')
theta, x_new = gradientDescentAutogradRegression(X, y, 0.01)
print('Theta:\n',theta,'\n')
pred = np.dot(x_new,theta)
print('Prediction:\n',pred,'\n')
rmse = mse_calc(y, pred)
print('RMSE=',rmse)

X:
 [[1 2 5]
 [3 1 9]
 [4 5 7]
 [2 6 4]
 [2 6 9]] 

y:
 [[ 8]
 [13]
 [16]
 [12]
 [17]] 



/usr/local/lib/python3.6/dist-packages/autograd/tracer.py:14: UserWarning: Output seems independent of input.
  warnings.warn("Output seems independent of input.")


Theta:
 [[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]] 

Prediction:
 [[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]] 

RMSE= [ 13.57939616]


# 4d

In [14]:
import torch
from torch.autograd import Variable

In [15]:
def gradientDescentPyTorchRegression(X, y, alpha = 0.1):
    n, m = X.shape[0], X.shape[1]
    ones = np.ones((n,1))
    X = np.hstack((ones,X))
    y = np.array([i for i in y])
    X = torch.from_numpy(X)
    y = torch.from_numpy(y)
    theta = Variable(torch.from_numpy(np.random.sample(X.shape[1])), 
                     requires_grad = True)
    
    iterations = 10**4
    
    for i  in range(iterations):
        er = torch.sum((y-torch.sum(X*theta, dim=1)) ** 2)
        er.backward()
        temp_tht = theta - (2*alpha/n)*theta.grad.data
        theta = Variable(temp_tht, requires_grad = True)
    return theta.data.numpy()


    

In [16]:
X = [[1,2,5],[3,1,9],[4,5,7],[2,6,4],[2,6,9]]

X = np.array([np.array(i) for i in X])
y = np.array([8,13,16,12,17])

y = y.reshape(len(y),1)

In [17]:
print('X:\n',X,'\n')
print('y:\n',y,'\n')
theta, x_new = gradientDescentAutogradRegression(X, y, 0.01)
print('Theta:\n',theta,'\n')
pred = np.dot(x_new,theta)
print('Prediction:\n',pred,'\n')
rmse = mse_calc(y, pred)
print('RMSE=',rmse)

X:
 [[1 2 5]
 [3 1 9]
 [4 5 7]
 [2 6 4]
 [2 6 9]] 

y:
 [[ 8]
 [13]
 [16]
 [12]
 [17]] 

Theta:
 [[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]] 

Prediction:
 [[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]] 

RMSE= [ 13.57939616]


# 4e

In [18]:
import time

In [19]:
real = pd.read_csv('Real estate valuation data set.csv')

In [20]:
X = real.copy()
del X['No']
y = X['house price of unit area']
del X['house price of unit area']
X

transaction date  house age  distance to the nearest MRT station  \
0            2012.917       32.0                             84.87882   
1            2012.917       19.5                            306.59470   
2            2013.583       13.3                            561.98450   
3            2013.500       13.3                            561.98450   
4            2012.833        5.0                            390.56840   
5            2012.667        7.1                           2175.03000   
6            2012.667       34.5                            623.47310   
7            2013.417       20.3                            287.60250   
8            2013.500       31.7                           5512.03800   
9            2013.417       17.9                           1783.18000   
10           2013.083       34.8                            405.21340   
11           2013.333        6.3                             90.45606   
12           2012.917       13.0                            492.23130   
13           2012.667       20.4                           2469.64500   
14           2013.500       13.2                           1164.83800   
15           2013.583       35.7                            579.20830   
16           2013.250        0.0                            292.99780   
17           2012.750       17.7                            350.85150   
18           2013.417       16.9                            368.13630   
19           2012.667        1.5                             23.38284   
20           2013.417        4.5                           2275.87700   
21           2013.417       10.5                            279.17260   
22           2012.917       14.7                           1360.13900   
23           2013.083       10.1                            279.17260   
24           2013.000       39.6                            480.69770   
25           2013.083       29.3                           1487.86800   
26           2012.667        3.1                            383.86240   
27           2013.250       10.4                            276.44900   
28           2013.500       19.2                            557.47800   
29           2013.083        7.1                            451.24380   
..                ...        ...                                  ...   
384          2012.750       16.1                           4066.58700   
385          2013.000       18.3                             82.88643   
386          2012.833        0.0                            185.42960   
387          2013.250       16.2                           2103.55500   
388          2013.500       10.4                           2251.93800   
389          2013.250       40.9                            122.36190   
390          2013.500       32.8                            377.83020   
391          2013.583        6.2                           1939.74900   
392          2013.083       42.7                            443.80200   
393          2013.000       16.9                            967.40000   
394          2013.500       32.6                           4136.27100   
395          2012.917       21.2                            512.54870   
396          2012.667       37.1                            918.63570   
397          2013.417       13.1                           1164.83800   
398          2013.417       14.7                           1717.19300   
399          2012.917       12.7                            170.12890   
400          2013.250       26.8                            482.75810   
401          2013.083        7.6                           2175.03000   
402          2012.833       12.7                            187.48230   
403          2012.667       30.9                            161.94200   
404          2013.333       16.4                            289.32480   
405          2012.667       23.0                            130.99450   
406          2013.167        1.9                            372

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
X_tr, X_ts, y_tr, y_ts = train_test_split(X, y, test_size=0.2, random_state=42)

In [23]:
X_train = np.zeros(( len(X_tr), len(X_tr.keys()) ))
keys = X_tr.keys()
for i in range(len(keys)):
    X_train[:,i] = X_tr[keys[i]]
X_test = np.zeros(( len(X_ts), len(X_ts.keys()) ))
for i in range(len(keys)):
    X_test[:,i] = X_ts[keys[i]]
y_train = np.array(y_tr).reshape((len(y_tr),1))
y_test = np.array(y_ts).reshape((len(y_ts),1))

X_t = np.hstack((np.ones((X_test.shape[0],1)), X_test))

In [24]:
#PyTorch
t1 = time.time()
theta_torch = gradientDescentPyTorchRegression(X_train,y_train)
t2 = time.time()
print(t2-t1)

KeyboardInterrupt: 

In [ ]:
pred = np.dot(X_t,theta_torch).reshape((len(pred),1))
rmse = mse_calc(y_test, pred)
print('RMSE=',rmse)

In [ ]:
#Autograd
t1 = time.time()
theta_autograg = gradientDescentAutogradRegression(X_train,y_train)
t2 = time.time()
print(t2-t1)

In [ ]:
pred = np.dot(X_t,theta_autograd).reshape((len(pred),1))
rmse = mse_calc(y_test, pred)
print('RMSE=',rmse)

In [ ]:
#Gradient Descent
t1 = time.time()
theta_grad = gradientDescentPyTorchRegression(X_train,y_train)
t2 = time.time()
print(t2-t1)

In [ ]:
pred = np.dot(X_t,theta_grad).reshape((len(pred),1))
rmse = mse_calc(y_test, pred)
s = 0
for i in range(len(y_test)):
    s += (y_test[i]-pred[i])**2
print('RMSE=',rmse)
print(s**0.5)
pred
theta_torch

In [25]:
#Normal Equation
t1 = time.time()
theta_torch = normalEquationRegression(X_train,y_train)
t2 = time.time()
print(t2-t1)

0.07794785499572754


In [26]:
pred = np.dot(X_t,theta_torch).reshape((len(pred),1))
rmse = mse_calc(y_test, pred)
s = 0
for i in range(len(y_test)):
    s += (y_test[i]-pred[i])**2
print('RMSE=',rmse)
print(s**0.5)
pred
theta_torch

ValueError: setting an array element with a sequence.